name: Publish to NPM

on:
  workflow_dispatch:
  push:
    paths:
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run build:test

      - name: Build the project
        run: npm run build

      - name: Set Npm Toknen
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish package to NPM
        run: npm publish || true

      - name: Unset Npm Toknen
        run: npm config delete //registry.npmjs.org/:_authToken
